CREATE TABLE CIDADE(
	id INT PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	UF VARCHAR(2) NOT NULL
)
GO
CREATE TABLE PESSOA(
	id INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(300) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	id_Cidade INT NOT NULL,
	idade INT NOT NULL
)
GO
ALTER TABLE [PESSOA] WITH CHECK ADD CONSTRAINT [PESSOA_fk0] FOREIGN KEY ([id_Cidade]) REFERENCES [CIDADE]([id])
GO
ALTER TABLE [PESSOA] CHECK CONSTRAINT [PESSOA_fk0]
GO